### ISSUE TITLE
Missing methods findOne

### ISSUE THREAD

**Issue by pedx78** [cdiniz/play-slick-rest#2]
Hi, very interesting template u have

However, i noticed that you call some methods in SuppliersController.scala

```
suppliersDAO.findOne
suppliersDAO.save
```

But you have not implemented above methods in your SupplierRepository.scala

**Comment by cdiniz** [comment]
Hi @pedx78, those methods are defined in an external library. Please take a look at the abstract class Repository, from slick-repo.
